### ISSUE TITLE
What we can learn from Neuron

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-wallet-and-explorer#23]
We have a full node wallet based on Electron.

We will have a backend supported wallet probably based on Electron too.

For the new coming product, we should learn something from the design of neuron.

Please write down your opinions about neuron from your code review these days. Something like

- Which thing neuron did is wrong
- What can we do to improve neuron

Anything would help.

**Comment by yanguoyu** [comment]
Can we create a comm package for the main process and render process? Then the API params can use the same interface. And they can use the same env or util functions.

**Comment by Keith-CY** [comment]
> Can we create a comm package for the main process and render process? Then the API params can use the same interface. And they can use the same env or util functions.

Definitely, we did it in other projects and got gorgeous benefit
Ref: https://github.com/nervosnetwork/keypering/blob/develop/packages/specs/src/api.ts

**Comment by Keith-CY** [comment]
Not going to launch `neuron lite`
