### ISSUE TITLE
Migrate Services

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-wallet-and-explorer#25]
- [x]  项目迁移
    - [x]  Neuron
        - [x]  Mac 证书
        - [x]  Windows 证书
        - [x]  Window 测试环境: 阿里云 → AWS
        - [x]  Linux 测试环境: 阿里云 → AWS
    - [x]  CKB 浏览器
        - [x]  主网:
            - [ ]  域名: [https://explorer.nervos.org/](https://explorer.nervos.org/) 迁移后修改 DNS
            - [x]  前端: Nervos AWS → AWS
            - [x]  后端: Nervos AWS → AWS
            - [x]  节点: Nervos AWS → AWS
        - [x]  测试网:
            - [ ]  域名: [https://explorer.nervos.org/aggron/](https://explorer.nervos.org/aggron/) 迁移后修改 DNS
            - [x]  前端: Nervos AWS → AWS
            - [x]  后端: Nervos AWS → AWS
            - [x]  节点: Nervos AWS → AWS
        - [x]  主网 staging:
            - [ ]  <del>域名: [https://explorer.staging.nervos.org/](https://explorer.staging.nervos.org/) 迁移后修改 DNS</del>
            - [x]  前端: Nervos AWS  → AWS
            - [x]  后端: Nervos AWS  → AWS
            - [x]  节点: Nervos AWS  → AWS
        - [x]  测试网 staging:
            - [ ]  <del>域名: [https://explorer.staging.nervos.org/aggron/](https://explorer.staging.nervos.org/aggron/) 迁移后修改 DNS</del>
            - [x]  前端: Nervos AWS → AWS
            - [x]  后端: Nervos AWS → AWS
            - [x]  节点: Nervos AWS → AWS
    - [x]  CKB 测试网水龙头
        - [x]  域名: [https://faucet.nervos.org/](https://faucet.nervos.org/) 迁移后修改 DNS
        - [x]  前端: Nervos AWS → AWS
        - [x]  后端: Nervos AWS → AWS
        - [x]  节点: Nervos AWS → AWS
    - [x]  Godwoken 浏览器
        - [x]  域名
            - [x]  gwscan.com
            - [x]  layerview.io
        - [x]  主网:
            - [x]  前端: Vercel → Vercel
            - [x]  后端: 阿里云 → AWS
            - [x]  节点: 阿里云 → AWS
        - [x]  测试网:
            - [x]  前端: Vercel → Vercel
            - [x]  后端: 阿里云 → AWS
            - [x]  节点: 阿里云 → AWS
        - [x]  staging:
            - [x]  前端: Vercel → Vercel
            - [x]  后端: 阿里云 → AWS
            - [x]  节点: 阿里云 → AWS

**Comment by Keith-CY** [comment]
迁移的服务还有哪些需要更新吗 @ShiningRay

**Comment by ShiningRay** [comment]
CKB Explorer 正式网预备 https://ckb-explorer.mainnet.layerview.io/
CKB Explorer 测试网预备 https://ckb-explorer.testnet.layerview.io/
CKB Explorer  测试环境 https://ckb-explorer.staging.layerview.io/

**Comment by Keith-CY** [comment]
Neuron 的测试环境可以访问了吗

**Comment by ShiningRay** [comment]
Faucet 已经迁移完成
更新过的仓库： https://github.com/Magickbase/ckb-testnet-faucet
