### ISSUE TITLE
A demo dapp like pool together 

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/ckb-wallet-and-explorer#27]
[pooltogether](https://pooltogether.com/zh)
https://github.com/nervosnet/ckb-wallet-and-explorer/issues/26

**Comment by Keith-CY** [comment]
Pooltogether has around 17 contracts in their Github, we may have to find out the core one and estimate its workload to deploy it on godwoken v1. Let's start the first step, finding out the core contract. I'll work on it too, let's update in this issue.

**Comment by yanguoyu** [comment]
We should develop it ourselves or fork and adapt their codes?

**Comment by Keith-CY** [comment]
> We should develop it ourselves or fork and adapt their codes?

Just work on their codebase. Our goal is to demonstrate how to use our public APIs to run an ETH DApp on Godwoken, but not develop our own DApp.

**Comment by yanguoyu** [comment]
[hardhat deploy plugin](https://github.com/wighawag/hardhat-deploy)

**Comment by Keith-CY** [comment]
PRD will be updated by 08/03

**Comment by Keith-CY** [comment]
Included in https://github.com/Magickbase/ckb-wallet-and-explorer/issues/27
